#!/bin/bash

#
# This script will teardown any underlying ZFS infrastructure that we may have installed on the
# host VM. It should be invoked with the same arguments as the launch script, and will do the
# following:
#
#   * Destroy the ZFS pool if it exists
#   * Undo any bind mounts
#   * Uninstall ZFS modules, if we were responsible for installing them in the first place
#   * Remove the local, including the underlying datafile
#
# It should be run as part of 'titan uninstall', as well as after endtoend tests. It is up to
# the user to make sure all repositories are destroyed prior to invoking this, otherwise it
# could get an EBUSY error.

source $(dirname $0)/zfs.sh
source $(dirname $0)/titan.sh
source $(dirname $0)/util.sh

if pool_exists $POOL; then
  echo "Destroying pool $POOL"
  destroy_pool $POOL  || log_error "Failed to destroy storage pool"
  rm -f $POOL_DIR/data || log_error "Failed to remove pool data file"
  rm -f $POOL_DIR/cachefile || log_error "Failed to remove pool cache file"
fi

echo "Unbinding mounts"
unbind_mounts $MNT_DIR
echo "Unloading ZFS"
unload_zfs $INSTALL_DIR || log_error "failed to unload ZFS module"
echo "Removing any lingering mountpoints"
rm -rf $MNT_DIR || log_error "failed to remove $MNT_DIR"
