#
# On each push, we do a full build and run a more complex set of end to end
# tests that take longer to run (and may require secrets like S3 credentials).
# End to end tests are still TBD, so for now this is just a full build
# (including the docker build, which is not done in PR context).
#
name: Push

on: push

jobs:
  build:
    name: Build and test
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8.0.212'
      - name: Build and test
        run: ./gradlew build
      - name: End to End tests
        run: |
          uname -a
          ./gradlew endtoendTest --tests *LocalWorkflowTest* --tests *S3WorkflowTest* --tests *SshWorkflowTest* -Ps3.location=${{ secrets.S3_TEST_LOCATION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
